#!/bin/sh

set -e

TARGET=172.16.0.10
IfIndexes=`snmpwalk -v 2c -c public $TARGET .1.3.6.1.2.1.2.2.1.1 | awk '{print $4}'`

TMP_PROBE_CONF=/tmp/probe.tmp
TMP_LOGGER_CONF=/tmp/logger.tmp
TMP_RRD_CREATE_CONF=/tmp/rrd_create.tmp
TMP_RRD_UPDATE_CONF1=/tmp/rrd_update1.tmp
TMP_RRD_UPDATE_CONF2=/tmp/rrd_update2.tmp


rm -f $TMP_PROBE_CONF $TMP_RRD_CREATE_CONF $TMP_RRD_UPDATE_CONF $TMP_RRD_GRAPH_CONF $TMP_LOGGER_CONF

for i in $IfIndexes
do
    ifInOctet="[1,3,6,1,2,1,2,2,1,10,$i,0]"
    ifOutOctet="[1,3,6,1,2,1,2,2,1,16,$i,0]"
    ifDescr=`snmpget -v 2c -c public $TARGET .1.3.6.1.2.1.2.2.1.2.$i \
        | awk -F'"' '{print $2}' | sed s/" "/"_"/g`
    ifType=`snmpget -v 2c -c public $TARGET .1.3.6.1.2.1.2.2.1.3.$i \
        | awk '{print $4}'`
    if [ $ifType != "24" ] # loopbacks
    then
        echo "{\"${ifDescr}-in\", $ifInOctet}," >> $TMP_PROBE_CONF
        echo "{\"${ifDescr}-out\", $ifOutOctet}," >> $TMP_PROBE_CONF
        echo "{\"${ifDescr}-in\", \"<${ifDescr}-in>\"}," >> $TMP_LOGGER_CONF
        echo "{\"${ifDescr}-out\", \"<${ifDescr}-out>\"}," >> $TMP_LOGGER_CONF
        echo -n " DS:${ifDescr}-in:COUNTER:10:U:U DS:${ifDescr}-out:COUNTER:10:U:U" \
            >> $TMP_RRD_CREATE_CONF
        echo -n "${ifDescr}-in:${ifDescr}-out:" \
            >> $TMP_RRD_UPDATE_CONF1
        echo -n "<${ifDescr}-in>:<${ifDescr}-out>:" \
            >> $TMP_RRD_UPDATE_CONF2
    fi
done

echo
echo
echo
echo
echo
echo "########################probe"
cat $TMP_PROBE_CONF | wc -m
echo "#####################logger"
cat $TMP_LOGGER_CONF | wc -m
echo "####################rrdcreate"
cat $TMP_RRD_CREATE_CONF | wc -m
echo "####################rrdupdate"
cat $TMP_RRD_UPDATE_CONF1 | wc -m
cat $TMP_RRD_UPDATE_CONF2 | wc -m
