#!/bin/bash
# sysmo daemon
# chkconfig: 345 20 80
# description: sysmo daemon
# processname: sysmo

DAEMON=myapp

NAME=sysmo
DESC="Sysmo System Management and Monitoring service"

# set SYSMO_SCRIPT to an absolute path if it is not present in the $PATH:
# example: /release_location/bin/sysmo
SYSMO_SCRIPT="sysmo"

restart_all() {
}

case "$1" in
  start)
    printf "%-50s" "Starting $NAME..."
    $SYSMO_SCRIPT start
    ;;
  stop)
    printf "%-50s" "Stopping $NAME"
    $SYSMO_SCRIPT stop
    ;;
  status)
    printf "%-50s" "Checking $NAME..."
    $SYSMO_SCRIPT eval
    ;;
  restart|reload)
    printf "%-50s" "Restarting $NAME"
    $SYSMO_SCRIPT reboot
    ;;
  *)
    echo "Usage: $0 {start|stop|restart|reload|status}"
    exit 1
esac
