# Makefile

EPATH      += -pa ebin
ERLC        = erlc -Werror
ASNC        = erlc -Werror -bber_bin +optimize +nif
ERL         = erl

APP         = $(subst ebin/,,$(basename $(wildcard ebin/*.app)))
INCLUDE     = $(wildcard ../include/*.hrl)

MAIN        = $(wildcard src/*.erl)
MAIN_DST    = $(patsubst src/%.erl, ebin/%.beam, $(MAIN))

AUTHS       = $(wildcard src/auths/*.erl)
AUTHS_DST   = $(patsubst src/auths/%.erl, ebin/%.beam, $(AUTHS))

ENCODERS    = $(wildcard src/encoders/*.erl)
ENCODERS_DST = $(patsubst src/encoders/%.erl, ebin/%.beam, $(ENCODERS))

ACCTRL      = $(wildcard src/acctrls/*.erl)
ACCTRL_DST  = $(patsubst src/acctrls/%.erl, ebin/%.beam, $(ACCTRL))

compile: $(MAIN_DST) $(AUTHS_DST) $(ENCODERS_DST) $(ACCTRL_DST) pdu


ebin/%.beam: src/%.erl $(INCLUDE)
	$(ERLC) $(EPATH) -o ebin/ src/$*.erl

ebin/%.beam: src/auths/%.erl
	$(ERLC) $(EPATH) -o ebin/ src/auths/$*.erl

ebin/%.beam: src/encoders/%.erl
	$(ERLC) $(EPATH) -o ebin/ src/encoders/$*.erl

ebin/%.beam: src/acctrls/%.erl
	$(ERLC) $(EPATH) -o ebin/ src/acctrls/$*.erl

clean:
	rm -f ebin/*.beam
	rm -f *.dump
	rm -f doc/*.html
	rm -f doc/*.png
	rm -f doc/*.css
	rm -f doc/edoc-info
	rm -f priv/asn1/build/*

clsupercast:
	@$(ERL) -pa ebin -eval \
 'clsupercast:s(), timer:sleep(500), clsupercast:adm()'

clsupercast2:
	@$(ERL) -pa ebin -eval \
 'clsupercast:s(), timer:sleep(500), clsupercast:std()'
# ASN PDUs
ASN_DEFS    = $(shell find priv/asn1 -name "*.asn")
ASN_DEST    = $(patsubst priv/asn1/%.asn, ebin/%.beam, $(ASN_DEFS))

pdu: $(ASN_DEST)

$(ASN_DEST): ebin/%.beam: priv/asn1/%.asn
	$(ASNC) -o priv/asn1/build priv/asn1/$*.asn
	@cp priv/asn1/build/$*.beam ebin
	@if `test -e priv/asn1/build/$*.hrl`; then cp priv/asn1/build/$*.hrl include; fi


# TEST
test: compile
	@$(ERL) -noinput -pa ebin -eval \
        'eunit:test(bsupercast_acctrl_rbac, [verbose]), init:stop()'

# DOCUMENTATION
doc: doc/index.html

doc/index.html: doc/overview.edoc src/*.erl
	@echo "Building documentation..."
	@$(ERL) -noinput -pa ebin -eval \
 'edoc:application($(APP), ".", []), init:stop()'
