% This file is part of "Enms" (http://sourceforge.net/projects/enms/)
% Copyright (C) 2012 <Sébastien Serre sserre.bx@gmail.com>
% 
% Enms is a Network Management System aimed to manage and monitor SNMP
% targets, monitor network hosts and services, provide a consistent
% documentation system and tools to help network professionals
% to have a wide perspective of the networks they manage.
% 
% Enms is free software: you can redistribute it and/or modify
% it under the terms of the GNU General Public License as published by
% the Free Software Foundation, either version 3 of the License, or
% (at your option) any later version.
% 
% Enms is distributed in the hope that it will be useful,
% but WITHOUT ANY WARRANTY; without even the implied warranty of
% MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
% GNU General Public License for more details.
% 
% You should have received a copy of the GNU General Public License
% along with Enms.  If not, see <http://www.gnu.org/licenses/>.
%%% This file was automatically generated by snmpc_mib_to_hrl version 4.22.1
%%% Date: 03-Sep-2012::12:05:11
-ifndef('SNMPv2-TM').
-define('SNMPv2-TM', true).

%% Oids

-define(snmpUDPDomain, [1,3,6,1,6,1,1]).

-define(snmpCLNSDomain, [1,3,6,1,6,1,2]).

-define(snmpCONSDomain, [1,3,6,1,6,1,3]).

-define(snmpDDPDomain, [1,3,6,1,6,1,4]).

-define(snmpIPXDomain, [1,3,6,1,6,1,5]).

-define(rfc1157Proxy, [1,3,6,1,6,2,1]).

-define(rfc1157Domain, [1,3,6,1,6,2,1,1]).

-define(snmpv2TM, [1,3,6,1,6,3,0]).


%% Range values


%% Default values

-endif.
