%% Generated by the Erlang ASN.1 compiler version:1.8
%% Purpose: Erlang record definitions for each named and unnamed
%% SEQUENCE and SET, and macro definitions for each value
%% definition,in module ModIf



-record('AuthAck',{
groups, staticChans}).

-record('AuthError',{
error, userId, pass}).

-record('AuthResp',{
userId, pass}).

-record('ChanInfo',{
channel, type}).

-record('ChanId',{
module, chan}).

