%% Generated by the Erlang ASN.1 compiler version:1.8
%% Purpose: Erlang record definitions for each named and unnamed
%% SEQUENCE and SET, and macro definitions for each value
%% definition,in module ModTracker



-record('ProbeInfo',{
channel, probeId, name, type, probeMod, status, step, timeoutMax, timeoutWait, inspectors, infoType}).

-record('ProbeDump',{
channel, probeId, probeType, rrdData}).

-record('ProbeFetch',{
channel, probe, probeType, probeValue}).

-record('TargetInfo',{
channel, hostname, ipAdd, tags, properties, type}).

-record('TargetCreate',{
ipAdd}).

-record('TargetUpdate',{
target}).

-record('TargetDelete',{
target}).

-record('ProbeCreate',{
target, probeMod}).

-record('ProbeUpdate',{
target, probe}).

-record('ProbeDelete',{
target, probe}).

