%% Generated by the Erlang ASN.1 compiler version:1.8
%% Purpose: Erlang record definitions for each named and unnamed
%% SEQUENCE and SET, and macro definitions for each value
%% definition,in module ModTracker



-record('ProbeInfo',{
channel, probe, status, name, type}).

-record('TargetInfo',{
channel, hostname, ipAdd, tags, properties, type}).

