#!/bin/sh

RT=`dirname $0`
OUT="$RT/htdocs/index.html"
HEAD="$RT/htemplates/head.template"
FOOT="$RT/htemplates/foot.template"
DATE=`date -R`

echo "Building website..."

##############################################################################
# HEADER                                                                     #
##############################################################################
cat $HEAD > $OUT

# LAST DATE MODIFIED
cat >> $OUT << EOF
    <div id="date">
        <em>Last time modified: $DATE</em>
    </div>
EOF

##############################################################################
# DOCUMENTATION                                                              #
##############################################################################
cat >> $OUT <<-EOF
    <div id="documentation">
        <h2>Documentation</h2>
        <ul>
EOF

for i in $@; do
    echo "          <li><a href='$i/index.html'>$i</a></li>" >> $OUT
done

cat >> $OUT <<-EOF
        </ul>
    </div>
EOF

##############################################################################
# FOOTER                                                                     #
##############################################################################
cat $FOOT >> $OUT
