ModTracker DEFINITIONS EXPLICIT TAGS ::=
BEGIN

TargetId        ::= PrintableString (SIZE (1..50))
TargetInfoType  ::= ENUMERATED {create(0), delete(1), update(2)}
ProbeType       ::= ENUMERATED {fetch(0), status(1)}
RRDFile         ::= OCTET STRING

ProbeInfo   ::= SEQUENCE {
    channel TargetId,
    probe   INTEGER,
    type    ProbeType,
    value   INTEGER
}

ProbeDump   ::= SEQUENCE {
    probe   ProbeInfo,
    rrdfile RRDFile
}

-- complete avec le tracker.hrl records finaux
TargetInfo  ::= SEQUENCE {
    channel  TargetId,
    type     TargetInfoType
}

TrackerPDU ::= CHOICE {
    fromServer  [0] CHOICE {
        targetInfo  [1] TargetInfo,
        probeInfo   [2] ProbeInfo,
        probeDump   [3] ProbeDump,
        ...
    },
    fromClient  [1] PrintableString
}

END
