#!/bin/sh

set -e

# go pping command
rm -rf sysmo/utils
mkdir  sysmo/utils
cp src/go/pping sysmo/utils/

# java helpers nodes
rm -rf sysmo/java_apps
mkdir  sysmo/java_apps
for app in errd4j snmpman nchecks equartz; do
    cp -R src/java/${app}/build/install/${app} sysmo/java_apps/
done

# nchecks xml files in config dir
rm -rf sysmo/etc/nchecks
cp -R sysmo/java_apps/nchecks/defs sysmo/etc/nchecks

# nchecks xml files in docroot
rm -rf sysmo/docroot/nchecks
cp -R sysmo/java_apps/nchecks/defs sysmo/docroot/nchecks
