#!/bin/sh
# -*- tab-width:4;indent-tabs-mode:nil -*-
# ex: ts=4 sw=4 et

RUNNER_SCRIPT_DIR=$(cd ${0%/*} && pwd -P)
SCRIPT=`basename $0`

case "$1" in
    start)
        ${RUNNER_SCRIPT_DIR}/sysmo start;;
    stop)
        ${RUNNER_SCRIPT_DIR}/sysmo stop;;
    restart)
        ${RUNNER_SCRIPT_DIR}/sysmo stop
        ${RUNNER_SCRIPT_DIR}/sysmo start;;
    ping)
        ${RUNNER_SCRIPT_DIR}/sysmo ping;;
    getpid)
        ${RUNNER_SCRIPT_DIR}/sysmo getpid;;
    *)
        echo "Usage: $SCRIPT {start|stop|restart|ping|getpid}";;
esac
