% This file is part of "Enms" (http://sourceforge.net/projects/enms/)
% Copyright (C) 2012 <Sébastien Serre sserre.bx@gmail.com>
% 
% Enms is a Network Management System aimed to manage and monitor SNMP
% targets, monitor network hosts and services, provide a consistent
% documentation system and tools to help network professionals
% to have a wide perspective of the networks they manage.
% 
% Enms is free software: you can redistribute it and/or modify
% it under the terms of the GNU General Public License as published by
% the Free Software Foundation, either version 3 of the License, or
% (at your option) any later version.
% 
% Enms is distributed in the hope that it will be useful,
% but WITHOUT ANY WARRANTY; without even the implied warranty of
% MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
% GNU General Public License for more details.
% 
% You should have received a copy of the GNU General Public License
% along with Enms.  If not, see <http://www.gnu.org/licenses/>.
%%% This file was automatically generated by snmpc_mib_to_hrl version 4.22.1
%%% Date: 03-Sep-2012::12:05:11
-ifndef('SNMP-MPD-MIB').
-define('SNMP-MPD-MIB', true).

%% Oids

-define(snmpMPDMIB, [1,3,6,1,6,3,11]).

-define(snmpMPDAdmin, [1,3,6,1,6,3,11,1]).

-define(snmpMPDMIBObjects, [1,3,6,1,6,3,11,2]).

-define(snmpMPDStats, [1,3,6,1,6,3,11,2,1]).
-define(snmpUnknownSecurityModels, [1,3,6,1,6,3,11,2,1,1]).
-define(snmpUnknownSecurityModels_instance, [1,3,6,1,6,3,11,2,1,1,0]).
-define(snmpInvalidMsgs, [1,3,6,1,6,3,11,2,1,2]).
-define(snmpInvalidMsgs_instance, [1,3,6,1,6,3,11,2,1,2,0]).
-define(snmpUnknownPDUHandlers, [1,3,6,1,6,3,11,2,1,3]).
-define(snmpUnknownPDUHandlers_instance, [1,3,6,1,6,3,11,2,1,3,0]).

-define(snmpMPDMIBConformance, [1,3,6,1,6,3,11,3]).

-define(snmpMPDMIBCompliances, [1,3,6,1,6,3,11,3,1]).

-define(snmpMPDMIBGroups, [1,3,6,1,6,3,11,3,2]).

-define(snmpMPDGroup, [1,3,6,1,6,3,11,3,2,1]).


%% Range values
-define(low_snmpUnknownSecurityModels, 0).
-define(high_snmpUnknownSecurityModels, 4294967295).
-define(low_snmpInvalidMsgs, 0).
-define(high_snmpInvalidMsgs, 4294967295).
-define(low_snmpUnknownPDUHandlers, 0).
-define(high_snmpUnknownPDUHandlers, 4294967295).


%% Default values
-define(default_snmpUnknownSecurityModels, 0).
-define(default_snmpInvalidMsgs, 0).
-define(default_snmpUnknownPDUHandlers, 0).

-endif.
