%% Generated by the Erlang ASN.1 compiler version:2.0.4
%% Purpose: Erlang record definitions for each named and unnamed
%% SEQUENCE and SET, and macro definitions for each value
%% definition,in module ModEsnmp



-record('TrapsTableRow',{
timeStamp, version, fromIp, fromPort, credentials, tags, message}).

