%% Generated by the Erlang ASN.1 compiler version:1.8
%% Purpose: Erlang record definitions for each named and unnamed
%% SEQUENCE and SET, and macro definitions for each value
%% definition,in module ModTracker



-record('PermConf',{
read, write}).

-record('TargetProperty',{
name, value}).

-record('ProbeConf',{
name, type}).

-record('ProbeInfo',{
channel, probeId, name, type, probeMod, status, step, timeoutMax, timeoutWait, inspectors, infoType}).

-record('ProbeModuleInfo',{
name, info}).

-record('ProbeDump',{
channel, probeId, probeType, rrdData}).

-record('ProbeFetch',{
channel, probe, probeType, probeValue}).

-record('TargetInfo',{
channel, properties, type}).

-record('CommandResponce',{
cmdId, cmdMsg}).

-record('TargetCreate',{
ipAdd, hostname, sysName, permConf, cmdId}).

-record('ProbeCreate',{
target, probeConf}).

-record('TargetUpdate',{
target}).

-record('TargetDelete',{
target}).

-record('ProbeUpdate',{
target, probe}).

-record('ProbeDelete',{
target, probe}).

