%% Generated by the Erlang ASN.1 compiler version:3.0.1
%% Purpose: Erlang record definitions for each named and unnamed
%% SEQUENCE and SET, and macro definitions for each value
%% definition,in module MonitorLoggerRrd



-ifndef(_MONITORLOGGERRRD_HRL_).
-define(_MONITORLOGGERRRD_HRL_, true).

-record('LoggerRrdIdToFile',{
index, fileName}).

-record('LoggerRrdUpdate',{
index, update}).

-record('LoggerRrdDump',{
target, probeName, probeModule, indexes, path}).

-record('LoggerRrdEvent',{
target, probeName, updates}).

-endif. %% _MONITORLOGGERRRD_HRL_
