%% Generated by the Erlang ASN.1 compiler version:1.8
%% Purpose: Erlang record definitions for each named and unnamed
%% SEQUENCE and SET, and macro definitions for each value
%% definition,in module ModEsnmp



-record('TrapsTableRow',{
timeStamp, version, fromIp, fromPort, credentials, tags, message}).

-record('IpAddr',{
o1, o2, o3, o4}).

-record('AgentConf',{
targetName, community, ipAddr, port, engineID, timeout, maxMessageSize, version, secModel, secName, secLevel}).

