%% Generated by the Erlang ASN.1 compiler version:1.8
%% Purpose: Erlang record definitions for each named and unnamed
%% SEQUENCE and SET, and macro definitions for each value
%% definition,in module ModIf



-record('Version',{
major, minor, patch}).

-record('IfPDU_fromServer_authAck',{
groups, modules}).

-record('IfPDU_fromServer_authError',{
error, userId, pass}).

-record('IfPDU_fromClient_authRep_localFile',{
userId, pass}).

-record('IfPDU_fromClient_authRep_ldap',{
userId, pass}).

